// DON'T EDIT THIS FILE.
// This file is auto generated by sbt-lock 0.2.3.
// https://github.com/tkawachi/sbt-lock/
dependencyOverrides in ThisBuild ++= Set(
  "com.chuusai" % "shapeless_2.12" % "2.3.2",
  "com.google.guava" % "guava" % "19.0",
  "jline" % "jline" % "2.14.1",
  "org.scala-lang.modules" % "scala-parser-combinators_2.12" % "1.0.4",
  "org.scala-lang.modules" % "scala-xml_2.12" % "1.0.6",
  "org.scala-sbt" % "test-interface" % "1.0",
  "org.scalacheck" % "scalacheck_2.12" % "1.13.4",
  "org.scalactic" % "scalactic_2.12" % "3.0.1",
  "org.scalatest" % "scalatest_2.12" % "3.0.1",
  "org.slf4j" % "slf4j-api" % "1.7.22",
  "org.typelevel" % "macro-compat_2.12" % "1.1.1",
  "org.whispersystems" % "curve25519-java" % "0.3.0"
)
// LIBRARY_DEPENDENCIES_HASH c2d699ca9f0a09da8369f96f1414e83b4c7f9f0e
