// DON'T EDIT THIS FILE.
// This file is auto generated by sbt-lock 0.3.0.
// https://github.com/tkawachi/sbt-lock/
dependencyOverrides in ThisBuild ++= Set(
  "com.google.guava" % "guava" % "19.0",
  "org.bouncycastle" % "bcprov-jdk15on" % "1.57",
  "org.slf4j" % "slf4j-api" % "1.7.25",
  "org.whispersystems" % "curve25519-java" % "0.4.1"
)
// LIBRARY_DEPENDENCIES_HASH 187809aa6d6649ce17fe756821bae5d6d28a84dc
